# Generated by Django 4.2.4 on 2023-10-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='version',
        ),
    ]
