# Generated by Django 4.2.4 on 2023-10-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_product_and_more'),
        ('products', '0012_productvariant_alter_price_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
