# Generated by Django 4.2.4 on 2023-10-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_discount_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='product_variant',
        ),
    ]
