# Generated by Django 4.2.4 on 2023-10-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('product', 'color')},
        ),
    ]
