# Generated by Django 4.2.4 on 2023-10-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='price',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcolor'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'product_color', 'version')},
        ),
        migrations.RemoveField(
            model_name='price',
            name='color',
        ),
    ]
