# Generated by Django 4.2.4 on 2023-10-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_price_unique_together_price_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='media_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], max_length=255),
        ),
    ]
