# Generated by Django 4.2.4 on 2023-10-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_gallery_media_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together={('media_type', 'image', 'youtube_embed', 'product')},
        ),
    ]
