# Generated by Django 4.2.4 on 2023-10-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, default='ci-folder', max_length=255, null=True),
        ),
    ]
